Public Class CLists
    Public companyNames As New Dictionary(Of String, Integer) From {
        {"DreamWorks Animation", 0},
        {"Legendary Pictures", 0},
        {"Warner Bros. Pictures", 0},
        {"Caper Film", 0},
        {"Metro-Goldwyn-Mayer", 0},
        {"Silver Pictures", 0},
        {"TF1 Studio", 0},
        {"Labyrinthe Films", 0},
        {"uMedia", 0},
        {"CJ Entertainment", 0},
        {"TPS Company", 0},
        {"CJ ENM", 0},
        {"Columbia Pictures", 0},
        {"di Bonaventura Pictures", 0},
        {"Illumination", 0},
        {"Andromeda Motion Pictures", 0},
        {"Thunder Road", 0},
        {"Capstone Studios", 0},
        {"Streamline Global", 0},
        {"Beijing Culture", 0},
        {"Century Changshengtian Film", 0},
        {"Tencent Penguin Pictures", 0},
        {"Maoyan Entertainment", 0},
        {"Huaxia Film Distribution", 0},
        {"Tetrad Productions", 0},
        {"DNA Films", 0},
        {"IPR.VC", 0},
        {"A24", 0},
        {"Scene23", 0},
        {"Altitude Film Entertainment", 0},
        {"Ingenious Media", 0},
        {"Hyprr Films", 0},
        {"Sarma Films", 0},
        {"Dimension Studio", 0},
        {"Luminaire Artisans", 0},
        {"NL Film en TV", 0},
        {"KRO-NCRV", 0},
        {"Signature Entertainment", 0},
        {"PCMA Productions", 0},
        {"Roth-Kirschenbaum Films", 0},
        {"Broken Open Pictures", 0},
        {"Volition Media Partners", 0},
        {"Highland Film Group", 0},
        {"Hoodlum Entertainment", 0},
        {"R.U. Robot Studios", 0},
        {"Moonbow", 0},
        {"Gosdom Entertainment", 0},
        {"Short Porch Pictures", 0},
        {"The Avenue Entertainment", 0}
    }
    Public genreDictionary As New Dictionary(Of Integer, String) From {
        {28, "Action"},
        {12, "Adventure"},
        {16, "Animation"},
        {35, "Comedy"},
        {80, "Crime"},
        {99, "Documentary"},
        {18, "Drama"},
        {10751, "Family"},
        {14, "Fantasy"},
        {36, "History"},
        {27, "Horror"},
        {10402, "Music"},
        {9648, "Mystery"},
        {10749, "Romance"},
        {878, "Science Fiction"},
        {10770, "TV Movie"},
        {53, "Thriller"},
        {10752, "War"},
        {37, "Western"}
    }
End Class
